Ontrack/ViewModels/ClassViewModel.cs
namespace Ontrack.ViewModels
{
    public class TeacherLandingPageViewModel
    {
        public string TeacherFullName { get; set; }
        public List<ClassViewModel> Classes { get; set; }
    }

    public class ClassViewModel
    {
        public string ClassName { get; set; }
        //public List<StudentViewModel> Students { get; set; }
        public List<StudentDetailViewModel> Students { get; set; }
    }


}

Ontrack/Controllers/ClassesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Ontrack.Data;
using Ontrack.Models;

namespace Ontrack.Controllers
{
    [Authorize(Roles = "Admin,Teacher")]
   
    public class ClassesController : Controller
    {
        private readonly SchoolContext _context;

        public ClassesController(SchoolContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> ClassStudentList()
        {
            var classesWithStudents = await _context.Classes
                .Include(c => c.Students)
                .ToListAsync();

            return View(classesWithStudents);
        }

        public async Task<IActionResult> Index(string searchString)
        {
            ViewData["CurrentFilter"] = searchString;

            var classes = _context.Classes
        .Include(c => c.Students) 
        .AsQueryable();

            if (!String.IsNullOrEmpty(searchString))
            {
                classes = classes.Where(c => c.ClassName.Contains(searchString));
            }

            return View(await classes.AsNoTracking().ToListAsync());
        }


        // GET: Classes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @class = await _context.Classes
                .FirstOrDefaultAsync(m => m.ClassID == id);
            if (@class == null)
            {
                return NotFound();
            }

            return View(@class);
        }

        // GET: Classes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Classes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClassID,ClassName")] Class @class)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@class);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@class);
        }

        // GET: Classes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @class = await _context.Classes.FindAsync(id);
            if (@class == null)
            {
                return NotFound();
            }
            return View(@class);
        }

        // POST: Classes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ClassID,ClassName")] Class @class)
        {
            if (id != @class.ClassID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@class);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClassExists(@class.ClassID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@class);
        }

        // GET: Classes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @class = await _context.Classes
                .FirstOrDefaultAsync(m => m.ClassID == id);
            if (@class == null)
            {
                return NotFound();
            }

            return View(@class);
        }

        // POST: Classes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @class = await _context.Classes.FindAsync(id);
            if (@class != null)
            {
                _context.Classes.Remove(@class);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClassExists(int id)
        {
            return _context.Classes.Any(e => e.ClassID == id);
        }
    }
}

Ontrack/Views/Classes/Create.cshtml
@model Ontrack.Models.Class

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Class</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ClassName" class="control-label"></label>
                <input asp-for="ClassName" class="form-control" />
                <span asp-validation-for="ClassName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Ontrack/Views/Classes/Delete.cshtml
@model Ontrack.Models.Class

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Class</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClassName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClassName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ClassID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Ontrack/Views/Classes/Details.cshtml
@model Ontrack.Models.Class

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Class</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClassName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClassName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ClassID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Ontrack/Views/Classes/Edit.cshtml
@model Ontrack.Models.Class

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Class</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ClassID" />
            <div class="form-group">
                <label asp-for="ClassName" class="control-label"></label>
                <input asp-for="ClassName" class="form-control" />
                <span asp-validation-for="ClassName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Ontrack/Views/Classes/Index.cshtml
@model IEnumerable<Ontrack.Models.Class>

@{
    ViewData["Title"] = "Classes Index";
}

<h1 class="text-center">Classes</h1>

@using (Html.BeginForm("Index", "Classes", FormMethod.Get))
{
    <div class="form-group row justify-content-center">
        <label for="searchString" class="col-form-label col-auto">Search:</label>
        <div class="col-auto">
            <input type="text" class="form-control form-control-sm" id="searchString" name="searchString" />
        </div>
        <div class="col-auto">
            <button type="submit" class="btn btn-primary btn-sm">Search</button>
        </div>
    </div>
}

<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.ClassName)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var cls in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => cls.ClassName)</td>
              
                <td>
                    <a asp-action="Details" asp-route-id="@cls.ClassID" class="btn btn-info">Details</a> |
                    <a asp-action="Edit" asp-route-id="@cls.ClassID" class="btn btn-info">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@cls.ClassID" class="btn btn-info">Delete</a>

                    <button  class="btn btn-info" type="button" data-toggle="collapse" data-target="#studentsInClass-@cls.ClassID" aria-expanded="false" aria-controls="studentsInClass-@cls.ClassID">
                        Show Students
                    </button>
                
                </td>
            </tr>
            <tr>
                <td colspan="3">
                    <div id="studentsInClass-@cls.ClassID" class="collapse">
                        @if (cls.Students != null && cls.Students.Any())
                        {
                            <table class="table table-sm table-bordered">
                                <thead>
                                    <tr>
                                        <th>First Name</th>
                                        <th>Last Name</th>
                                        <th>Date of Birth</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var student in cls.Students)
                                    {
                                        <tr>
                                            <td>@student.FirstName</td>
                                            <td>@student.LastName</td>
                                            <td>@student.DOB.ToString("yyyy-MM-dd")</td>
                                            <td>
                                                <a asp-controller="Students" asp-action="Details" asp-route-id="@student.StudentID" class="btn btn-sm btn-info">Details</a> |
                                                <a asp-controller="Students" asp-action="Edit" asp-route-id="@student.StudentID" class="btn btn-sm btn-warning">Edit</a> |
                                                <a asp-controller="Students" asp-action="Delete" asp-route-id="@student.StudentID" class="btn btn-sm btn-danger">Delete</a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        }
                        else
                        {
                            <p>No students found for this class.</p>
                        }

                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

<p class="text-center">
    <a asp-action="Create" class="btn m-1 btn-primary">Create New</a>
</p>

<!-- Bootstrap JS and dependencies -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<script>
    $(document).ready(function () {
        $('.collapse').on('show.bs.collapse', function () {
            $(this).parent().find('button').text('Hide Students');
        }).on('hide.bs.collapse', function () {
            $(this).parent().find('button').text('Show Students');
        });
    });
</script>

Ontrack/Views/Classes/classesWithStudents.cshtml
@model IEnumerable<Ontrack.Models.Class>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Class Students List</title>
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="container mt-4">
        @foreach (var classItem in Model)
        {
            <div class="accordion" id="classAccordion">
                <div class="card">
                    <div class="card-header" id="headingClass_@classItem.ClassID">
                        <h2 class="mb-0">
                            <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapseClass_@classItem.ClassID" aria-expanded="false" aria-controls="collapseClass_@classItem.ClassID">
                                <strong>@classItem.ClassName - Show Students</strong>
                            </button>
                        </h2>
                    </div>

                    <div id="collapseClass_@classItem.ClassID" class="collapse" aria-labelledby="headingClass_@classItem.ClassID" data-parent="#classAccordion">
                        <div class="card-body" style="border: 1px solid #ccc; padding: 10px; background-color: #f9f9f9; font-size: 14px;">
                            <h4>Students in @classItem.ClassName</h4>

                            @if (classItem.Students != null && classItem.Students.Any())
                            {
                                <table class="table table-sm table-bordered" style="width: 90%; margin: 0 auto;">
                                    <thead>
                                        <tr>
                                            <th>First Name</th>
                                            <th>Last Name</th>
                                            <th>Date of Birth</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var student in classItem.Students)
                                        {
                                            <tr>
                                                <td>@student.FirstName</td>
                                                <td>@student.LastName</td>
                                                <td>@student.DOB.ToString("yyyy-MM-dd")</td>
                                                <td>
                                                    <a asp-controller="Students" asp-action="Details" asp-route-id="@student.StudentID" class="btn btn-sm btn-info">Details</a>
                                                    <a asp-controller="Students" asp-action="Edit" asp-route-id="@student.StudentID" class="btn btn-sm btn-warning">Edit</a>
                                                    <a asp-controller="Students" asp-action="Delete" asp-route-id="@student.StudentID" class="btn btn-sm btn-danger">Delete</a>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            }
                            else
                            {
                                <p>No students found for this class.</p>
                            }
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="~/lib/popper.js/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#classAccordion .collapse').on('show.bs.collapse', function () {
                $(this).parent().find('.btn-link').text('Hide Students');
            }).on('hide.bs.collapse', function () {
                $(this).parent().find('.btn-link').text('Show Students');
            });
        });
    </script>
</body>
</html>